version: '2.1'
#Note the .env file with variables

services:
    gs:
        image: osgeo4inspire/geoserver-bsg
        links:
            - postgis:postgis 
        container_name: geoserver
        depends_on:
            postgis:
              condition: service_healthy 
        ports:
            - "8080:8080"
    postgis:
        image: osgeo4inspire/postgis-bsg
        healthcheck:
            test: ["CMD", "nc", "-zv", "localhost", "5432"]
            interval: 30s
            timeout: 10s
            retries: 5
        container_name: postgis
